CREATE TABLE IF NOT EXISTS productos_cafeteria(
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    referencia VARCHAR(255) NOT NULL,
    precio  DECIMAL(9,2) NOT NULL,
    peso  DECIMAL(9,2) NOT NULL,
    categoria  VARCHAR(255) NOT NULL,
    stock  TINYINT NOT NULL,
    fecha  DATE NOT NULL
);